language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lcov

before_script:
  - mkdir build
  - cd build
  - cmake -DCHAOS_ARCHITECTURE_TEST=ON -DCMAKE_BUILD_TYPE=PROFILE ..

script:
    - make install
    - export LD_LIBRARY_PATH=/chaosframework/chaos-distrib-x86_64-Linux/lib
    - chaos-distrib-x86_64-Linux/bin/TestFramework
